In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array(50)
print(a)
print(type(a))
print(a.ndim)

50
<class 'numpy.ndarray'>
0


In [4]:
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [6]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(a)
print(type(a))
print(a.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
3


In [7]:
e=np.array([4,6.7,"python",7+8j,True,False])
print(e)
print(type(e))
print(e.ndim)

['4' '6.7' 'python' '(7+8j)' 'True' 'False']
<class 'numpy.ndarray'>
1


In [8]:
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(a+b)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [9]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a+b)

[ 6  8 10 12 14]


In [10]:
c=sum(a)
print(c)
d=sum(b)
print(d)

15
35


In [11]:
f=np.mean(a)
print(f)
g=np.mean(b)
print(g)

3.0
7.0
